import { FlowContext } from '../src/types/flow.types'

export const TEST_INSTANCE: FlowContext = {
  state: 'running',
  context: {
    limit: 20,
    assets: [
      {
        id: 352582692,
        num_sales: 0,
        background_color: null,
        image_url:
          'https://lh3.googleusercontent.com/1c1zSlpg78UD5hQOcdvg-ZsVm_L4WeW2YS7hz4qtjUTuDFV3ZMKojPAVMDri13_5fjVWq5tSV6OJRDJiKN3U-90pDgHbNbEtFiJRJ90',
        image_preview_url:
          'https://lh3.googleusercontent.com/1c1zSlpg78UD5hQOcdvg-ZsVm_L4WeW2YS7hz4qtjUTuDFV3ZMKojPAVMDri13_5fjVWq5tSV6OJRDJiKN3U-90pDgHbNbEtFiJRJ90=s250',
        image_thumbnail_url:
          'https://lh3.googleusercontent.com/1c1zSlpg78UD5hQOcdvg-ZsVm_L4WeW2YS7hz4qtjUTuDFV3ZMKojPAVMDri13_5fjVWq5tSV6OJRDJiKN3U-90pDgHbNbEtFiJRJ90=s128',
        image_original_url:
          'https://gateway.pinata.cloud/ipfs/QmNVvZq7wQpRxEVSnGTxAkhcU6cn3SCgSgzpqUtKaBmF6y',
        animation_url: null,
        animation_original_url: null,
        name: 'Adam',
        description:
          'This is diypunk Adam - let your creativity run wild and decide for yourself what your punk should look like: serious, crazy, funny, colorful, absolutely individual! diypunks is committed to the fact that everyone should have a tailor-made punk. There are 200 elements waiting for you, and any color you want. Start now via https://diypunks.xyz',
        external_link: null,
        asset_contract: {
          address: '0x1cab270555a15320fac9326ce7ff05f5d8ddd4ca',
          asset_contract_type: 'non-fungible',
          created_date: '2022-03-27T04:49:58.846473',
          name: 'DiyPunks',
          nft_version: '3.0',
          opensea_version: null,
          owner: 1468236,
          schema_name: 'ERC721',
          symbol: 'DIYP',
          total_supply: null,
          description: '',
          external_link: 'https://diypunks.xyz',
          image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s120',
          default_to_fiat: false,
          dev_buyer_fee_basis_points: 0,
          dev_seller_fee_basis_points: 0,
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: 0,
          opensea_seller_fee_basis_points: 250,
          buyer_fee_basis_points: 0,
          seller_fee_basis_points: 250,
          payout_address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
        },
        permalink:
          'https://opensea.io/assets/ethereum/0x1cab270555a15320fac9326ce7ff05f5d8ddd4ca/1',
        collection: {
          banner_image_url: null,
          chat_url: null,
          created_date: '2022-03-27T06:26:54.875187',
          default_to_fiat: false,
          description: '',
          dev_buyer_fee_basis_points: '0',
          dev_seller_fee_basis_points: '0',
          discord_url: null,
          display_data: { card_display_style: 'contain' },
          external_url: 'https://diypunks.xyz',
          featured: false,
          featured_image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s300',
          hidden: false,
          safelist_request_status: 'not_requested',
          image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s120',
          is_subject_to_whitelist: false,
          large_image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s300',
          medium_username: null,
          name: 'DiyPunks',
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: '0',
          opensea_seller_fee_basis_points: '250',
          payout_address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          require_email: false,
          short_description: null,
          slug: 'diypunks',
          telegram_url: null,
          twitter_username: null,
          instagram_username: null,
          wiki_url: null,
          is_nsfw: false,
        },
        decimals: 0,
        token_metadata:
          'https://gateway.diypunks.xyz/ipfs/QmQnBxGuRUdtt6486Ykq9VWbGNLFqTxh8x6vRtjCDmSvuo',
        is_nsfw: false,
        owner: {
          user: { username: 'urbanisierung' },
          profile_img_url:
            'https://storage.googleapis.com/opensea-static/opensea-profile/5.png',
          address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          config: '',
        },
        sell_orders: null,
        seaport_sell_orders: null,
        creator: {
          user: { username: 'urbanisierung' },
          profile_img_url:
            'https://storage.googleapis.com/opensea-static/opensea-profile/5.png',
          address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          config: '',
        },
        traits: [
          {
            trait_type: 'Background',
            value: 'Midnight',
            display_type: null,
            max_value: null,
            trait_count: 11,
            order: null,
          },
          {
            trait_type: 'Eye Accessory',
            value: 'Nerd Glasses',
            display_type: null,
            max_value: null,
            trait_count: 8,
            order: null,
          },
          {
            trait_type: 'Hair',
            value: 'Messy Hair',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'Badge Top Right',
            value: 'Developer DAO',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'name',
            value: 'Adam',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'Base',
            value: 'Ser',
            display_type: null,
            max_value: null,
            trait_count: 13,
            order: null,
          },
          {
            trait_type: 'Eye',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 19,
            order: null,
          },
          {
            trait_type: 'Nose',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 18,
            order: null,
          },
          {
            trait_type: 'Mouth',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 8,
            order: null,
          },
          {
            trait_type: 'pixeltype',
            value: 'square',
            display_type: null,
            max_value: null,
            trait_count: 20,
            order: null,
          },
          {
            trait_type: 'Mint Date',
            value: '2022-03',
            display_type: null,
            max_value: null,
            trait_count: 16,
            order: null,
          },
        ],
        last_sale: null,
        top_bid: null,
        listing_date: null,
        is_presale: false,
        transfer_fee_payment_token: null,
        transfer_fee: null,
        token_id: '1',
      },
      {
        id: 352553663,
        num_sales: 0,
        background_color: null,
        image_url:
          'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ',
        image_preview_url:
          'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s250',
        image_thumbnail_url:
          'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s128',
        image_original_url:
          'https://gateway.pinata.cloud/ipfs/QmPJ2KseWBeH18jChkNyFXEGV3ys92mfZzNY5FiMyuJk6j',
        animation_url: null,
        animation_original_url: null,
        name: '#1',
        description:
          'This is diypunk #1 - let your creativity run wild and decide for yourself what your punk should look like: serious, crazy, funny, colorful, absolutely individual! diypunks is committed to the fact that everyone should have a tailor-made punk. There are 200 elements waiting for you, and any color you want. Start now via https://diypunks.xyz',
        external_link: null,
        asset_contract: {
          address: '0x1cab270555a15320fac9326ce7ff05f5d8ddd4ca',
          asset_contract_type: 'non-fungible',
          created_date: '2022-03-27T04:49:58.846473',
          name: 'DiyPunks',
          nft_version: '3.0',
          opensea_version: null,
          owner: 1468236,
          schema_name: 'ERC721',
          symbol: 'DIYP',
          total_supply: null,
          description: '',
          external_link: 'https://diypunks.xyz',
          image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s120',
          default_to_fiat: false,
          dev_buyer_fee_basis_points: 0,
          dev_seller_fee_basis_points: 0,
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: 0,
          opensea_seller_fee_basis_points: 250,
          buyer_fee_basis_points: 0,
          seller_fee_basis_points: 250,
          payout_address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
        },
        permalink:
          'https://opensea.io/assets/ethereum/0x1cab270555a15320fac9326ce7ff05f5d8ddd4ca/0',
        collection: {
          banner_image_url: null,
          chat_url: null,
          created_date: '2022-03-27T06:26:54.875187',
          default_to_fiat: false,
          description: '',
          dev_buyer_fee_basis_points: '0',
          dev_seller_fee_basis_points: '0',
          discord_url: null,
          display_data: { card_display_style: 'contain' },
          external_url: 'https://diypunks.xyz',
          featured: false,
          featured_image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s300',
          hidden: false,
          safelist_request_status: 'not_requested',
          image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s120',
          is_subject_to_whitelist: false,
          large_image_url:
            'https://lh3.googleusercontent.com/4TpbM0jeOOBdagEBu1cyzyNrs-E2RaqZyxhTwb5R7YQcoeRIO52YLPD6bCbOT6XVgoQU6ylyCxx75ZbtkeAFqIJUh2yKpCZEtKTqVQ=s300',
          medium_username: null,
          name: 'DiyPunks',
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: '0',
          opensea_seller_fee_basis_points: '250',
          payout_address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          require_email: false,
          short_description: null,
          slug: 'diypunks',
          telegram_url: null,
          twitter_username: null,
          instagram_username: null,
          wiki_url: null,
          is_nsfw: false,
        },
        decimals: 0,
        token_metadata:
          'https://gateway.diypunks.xyz/ipfs/QmXCSyj4EyPo8QB9H8qwSZvffWME3oH12QeEcfzJBFCcEe',
        is_nsfw: false,
        owner: {
          user: { username: 'urbanisierung' },
          profile_img_url:
            'https://storage.googleapis.com/opensea-static/opensea-profile/5.png',
          address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          config: '',
        },
        sell_orders: null,
        seaport_sell_orders: null,
        creator: {
          user: { username: 'urbanisierung' },
          profile_img_url:
            'https://storage.googleapis.com/opensea-static/opensea-profile/5.png',
          address: '0xa3fa175140c9779d5293e876a9c71ef10a7a0bd2',
          config: '',
        },
        traits: [
          {
            trait_type: 'Background',
            value: 'Purple',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'Base',
            value: 'Ser',
            display_type: null,
            max_value: null,
            trait_count: 13,
            order: null,
          },
          {
            trait_type: 'Eye',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 19,
            order: null,
          },
          {
            trait_type: 'Nose',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 18,
            order: null,
          },
          {
            trait_type: 'Mouth',
            value: 'Regular',
            display_type: null,
            max_value: null,
            trait_count: 8,
            order: null,
          },
          {
            trait_type: 'Eye Accessory',
            value: '3d Glasses',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'name',
            value: '#1',
            display_type: null,
            max_value: null,
            trait_count: 1,
            order: null,
          },
          {
            trait_type: 'pixeltype',
            value: 'square',
            display_type: null,
            max_value: null,
            trait_count: 20,
            order: null,
          },
          {
            trait_type: 'Mint Date',
            value: '2022-03',
            display_type: null,
            max_value: null,
            trait_count: 16,
            order: null,
          },
        ],
        last_sale: null,
        top_bid: null,
        listing_date: null,
        is_presale: false,
        transfer_fee_payment_token: null,
        transfer_fee: null,
        token_id: '0',
      },
    ],
  },
  next: ['2', '4'],
  log: [
    { id: '1', ts: 1656683145366, type: 'in' },
    { id: '1', ts: 1656683145401, type: 'prepared' },
    { id: '1', ts: 1656683145868, type: 'out' },
    { id: '2', ts: 1656683145868, type: 'in' },
    { id: '3', ts: 1656683145869, type: 'in' },
    { id: '2', ts: 1656683145902, type: 'prepared' },
    { id: '3', ts: 1656683145913, type: 'prepared' },
    { id: '3', ts: 1656683146089, type: 'out' },
  ],
  incoming: [{ id: '4', in: ['3'] }],
  errors: [
    {
      data: 'invalid_blocks',
      resolved: false,
      ts: 1656683146105,
      type: 'http',
      error: 'Request failed with status code 400',
      id: '2',
    },
  ],
  executingNodeIds: [],
}
