name: "[PROD] Publish Templates"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-templates:
    uses: ./.github/workflows/template-publish-npm-package.yaml
    with:
      packageDir: ./packages/templates
      packageScope: "@flethy/templates"
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
